In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import string
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import fnmatch
import json
import re
%matplotlib inline
import os

In [2]:
os.chdir('D:\\INSOFE\\CSE 7124c Text Mining\\HOT\\Combined')
os.getcwd()

'D:\\INSOFE\\CSE 7124c Text Mining\\HOT\\Combined'

In [3]:
path =r'D:\\INSOFE\\CSE 7124c Text Mining\\HOT\\Combined'

def ffilter(files, pattern, root, i):
    data=[]
    for fname in fnmatch.filter(files, pattern):
        data_file = open(os.path.join(root, fname), "r")
        text = data_file.read();
        data.append(text) 
    doc = pd.DataFrame(data)
    doc[1] = i
    return(doc);

In [4]:
for root, dirnames, filenames in os.walk(path):
    d1 = ffilter(filenames, '*_1', root, 1) 
    d2 = ffilter(filenames, '*_2', root, 2)
    d3 = ffilter(filenames, '*_3', root, 3)
    d4 = ffilter(filenames, '*_4', root, 4)
    d5 = ffilter(filenames, '*_5', root, 5)
    d6 = ffilter(filenames, '*_6', root, 6)
df = [d1, d2, d3, d4, d5, d6]
data_set = pd.concat(df, ignore_index=True)
data_set.columns = ['Text', 'Document']

In [5]:
d1.head(10)

0  1
0  \n\nArchive-name: atheism/resources\n\nAlt-ath...  1
1  \n\nArchive-name: atheism/introduction\n\nAlt-...  1
2  \n\nIn article <65974@mimsy.umd.edu>\n\nmangoe...  1
3  \n\ndmn@kepler.unh.edu (...until kings become ...  1
4  \n\nIn article <N4HY.93Apr5120934@harder.ccr-p...  1
5  \n\nIn article <1993Apr5.091139.823@batman.bmd...  1
6  NNTP-Posting-Host: punisher.caltech.edu\n\n\n\...  1
7  \n\nIn article <114127@bu.edu>\n\njaeger@buphy...  1
8  Message-ID: <1pi8h5INNq40@gap.caltech.edu>\n\n...  1
9  NNTP-Posting-Host: punisher.caltech.edu\n\n\n\...  1

In [6]:
print(len(d1)+len(d2)+len(d3)+len(d4)+len(d5)+len(d6))

5984


In [7]:
print(data_set.shape)

(5984, 2)


In [20]:
print(type(data_set.Text))

<class 'pandas.core.series.Series'>


In [12]:
print(data_set.head(10))

                                                Text  Document
0  \n\nArchive-name: atheism/resources\n\nAlt-ath...         1
1  \n\nArchive-name: atheism/introduction\n\nAlt-...         1
2  \n\nIn article <65974@mimsy.umd.edu>\n\nmangoe...         1
3  \n\ndmn@kepler.unh.edu (...until kings become ...         1
4  \n\nIn article <N4HY.93Apr5120934@harder.ccr-p...         1
5  \n\nIn article <1993Apr5.091139.823@batman.bmd...         1
6  NNTP-Posting-Host: punisher.caltech.edu\n\n\n\...         1
7  \n\nIn article <114127@bu.edu>\n\njaeger@buphy...         1
8  Message-ID: <1pi8h5INNq40@gap.caltech.edu>\n\n...         1
9  NNTP-Posting-Host: punisher.caltech.edu\n\n\n\...         1


In [26]:
data_set.tail(10)

Text  Document
5974  \n\n\n\n   I  must  finally  admit the total t...         6
5975  Sender: usenet@xn.ll.mit.edu\n\nReply-To: egge...         6
5976  Nntp-Posting-Host: watnxt13.ucr.edu\n\n\n\nSer...         6
5977  Nntp-Posting-Host: watnxt04.ucr.edu\n\n\n\nWel...         6
5978  Date: 25 May 93 07:12:02 GMT\n\nReferences: <1...         6
5979  \n\nIn article <1th4mg$53f@usenet.INS.CWRU.Edu...         6
5980  \n\nIn article <1993May24.165636.29928@cirrus....         6
5981  Distribution: world\n\nMessage-ID: <OAF.93May2...         6
5982  Message-ID: <OAF.93May25095940@klosters.ai.mit...         6
5983  \n\nIn article <3044@cronos.metaphor.com> covd...         6

In [9]:
df = data_set.sample(frac=1)

In [10]:
df.head(10)

Text  Document
1402  \n\najc@philabs.philips.com (Alec Cameron) wri...         2
2968  \n\nI want to run SPICE on my XT so I can lear...         3
5665  Distribution: world\n\nMessage-ID: <1qum5sINNe...         6
724   \n\nIn article <healta.140.734925835@saturn.ww...         1
667   \n\nIn article <C5L184.Jo9@news.cso.uiuc.edu>,...         1
1080  \n\nIn rec.autos, CPKJP@vm.cc.latech.edu (Kevi...         2
2435  \n\nAny info on modern 20MHZ or better dual tr...         3
5216  Distribution: world\n\nMessage-ID: <1qmdtlINNk...         6
3480  \n\n------------- cut here -----------------\n...         4
3381  Message-ID: <1r0vjf$op7@hsdndev.harvard.edu>\n...         4

In [11]:
df.tail(10)

Text  Document
1547  Date: 23 Apr 93 18:10:38 GMT\n\nReferences: <1...         2
3157  \n\nIn article <47974@sdcc12.ucsd.edu> wsun@je...         4
3081  \n\nIn article <1993Mar29.130824.16629@aoa.aoa...         4
2878  \n\njackp@NETSYS.COM (Jack Powers) writes:\n\n...         3
793   \n\n---\n\n[I'm taking talk.abortion out of th...         1
1750  Message-ID: <Apr17.054325.15482@engr.washingto...         2
328   Sender: news@saturn.wwc.edu (Net News Admin)\n...         1
5296  \n\nToday marks the 78th anniversary of the Ar...         6
3652  Message-ID: <1rgohb$fjr@hsdndev.harvard.edu>\n...         4
2084  \n\nIn article <1993Apr6.132429.16154@bnr.ca>\...         3

In [13]:
text_data = df['Text']
text_list = text_data.tolist()   

In [14]:
for i in range(len(text_list)):
    text_list[i] = re.sub(r'\s+', ' ', text_list[i]) #Removing more than one white spaces in the sentence
    text_list[i] = re.sub('[\d]', '', text_list[i]) #Removing numbers
    text_list[i] = re.sub("\n", '', text_list[i])

In [15]:
#look for 2 or more repetitions of character
recc = re.compile(r"(.)\1{1,}", re.DOTALL)

In [17]:
for i in range(len(text_list)):
    text_list[i]= recc.sub(r"\1\1", text_list[i])
    text_list[i]= text_list[i].lower()
    text_list[i] = text_list[i].strip('\'"?,.')
    text_list[i] =re.sub(r'[^a-zA-Z]',r' ', text_list[i])
print(text_list[0:20])

[' ajc philabs philips com  alec cameron  writes  for sale  norelco hot curlers  asking  contact alec cameron  x  alec cameron  ajc philabs philips com i know this is the  s but what is a man doing with hot curlers  chintan amin  the university of illinois urbanachampaign  mail  llama uiuc edu  sig under construction hard hat area  ', ' i want to run spice on my xt so i can learn more about amplifiers and oscilators  is there a version of this that will run on my xt with no math co processer  if so where can i get it  thanks for any and all help  jeff  jeff jones abmb  oppose the north american free trade agreement  jeffj seeker mystic com  canada usa free trade cost canada  jobs  infolinc bbs  want to guess how many we ll lose to mexico  ', 'distribution  world message id  qumsinneqi early bird think com  references  igc apc org  nntp posting host  composer think com in article  igc apc org  center for policy research  cpr igc apc org  writes  from  center for policy research  cpr  su

In [18]:
cln_data = pd.DataFrame(text_list)

In [19]:
cln_data.columns = ['Text']
cln_data = cln_data.Text.apply(lambda x: ' '.join([w for w in x.split() if len(w)>2]))

In [20]:
text_list = cln_data.tolist()
text_list[0:10]

['ajc philabs philips com alec cameron writes for sale norelco hot curlers asking contact alec cameron alec cameron ajc philabs philips com know this the but what man doing with hot curlers chintan amin the university illinois urbanachampaign mail llama uiuc edu sig under construction hard hat area',
 'want run spice can learn more about amplifiers and oscilators there version this that will run with math processer where can get thanks for any and all help jeff jeff jones abmb oppose the north american free trade agreement jeffj seeker mystic com canada usa free trade cost canada jobs infolinc bbs want guess how many lose mexico',
 'distribution world message qumsinneqi early bird think com references igc apc org nntp posting host composer think com article igc apc org center for policy research cpr igc apc org writes from center for policy research cpr subject unconventional peace proposal unconventional proposal for peace the middle east elias davidsson this could accomplished other 

In [31]:
import nltk

In [32]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kalya\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [35]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\kalya\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [36]:
all_words = []
sub_list = []
for item in text_list:
    tokenized = nltk.word_tokenize(item)
    tagged = nltk.pos_tag(tokenized)
    allowed = ['JJ']
    for w in tagged:
        if w[1] in allowed:
            all_words.append(w[0])
    all_words.append(sub_list)
print(all_words)

['ajc', 'alec', 'hot', 'hot', 'urbanachampaign', 'uiuc', 'hard', [], 'want', 'north', 'american', 'free', 'mystic', 'usa', 'free', 'many', [], 'early', 'apc', 'subject', 'unconventional', 'unconventional', 'middle', 'other', 'alternative', 'financial', 'sexual', 'different', 'ethnic', 'peace', 'sexual', 'short', 'israeli', 'screwed', 'palestinian', 'deductible', 'domestic', 'israeli', 'voluntary', 'palestinian', 'financial', 'incentive', 'suitable', 'critical', 'meaningful', [], 'wwc', 'make', 'human', 'wicked', 'real', 'tyre', 'bible', 'mad', 'mundane', 'ezekiel', 'sandvik', 'private', [], 'uiuc', 'uiuc', 'wonderful', 'imaginative', 'imaginative', 'spontaneous', 'non', 'imaginative', 'believable', 'giant', 'big', 'middle', 'illinois', 'urbana', 'uiuc', 'new', 'atal', 'mae', [], 'latech', 'enough', 'important', 'low', 'stylish', 'nice', 'don', 'much', 'many', 'fast', [], 'info', 'modern', 'dual', 'new', 'please', 'ken', 'rochester', 'new', 'uupsi', [], 'early', 'bbh', 'edu', 'edu', 'ap

In [39]:
len(all_words)

172165

In [45]:
all_words[:20]

['ajc',
 'alec',
 'hot',
 'hot',
 'urbanachampaign',
 'uiuc',
 'hard',
 [],
 'want',
 'north',
 'american',
 'free',
 'mystic',
 'usa',
 'free',
 'many',
 [],
 'early',
 'apc',
 'subject']

In [51]:
y = df['Document']
X = pd.DataFrame(text_list)
X.columns = ['Text']
y.columns=['Document']

In [52]:
#Using the train_test_split to create train and test sets.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state =123, test_size = 0.3)

In [53]:
print(y_train.value_counts())
print(y_test.value_counts())

1    726
2    703
5    702
6    700
3    689
4    668
Name: Document, dtype: int64
4    321
3    310
2    303
5    295
6    293
1    274
Name: Document, dtype: int64


In [54]:
print(X_train.head())
print(X_train.tail())
print(y_train.head())
print(y_train.tail())

                                                   Text
4586  rirv jfl msuinfo msu edu newman cps msu edu ti...
5713  article apr magnus acs ohio state edu bqueiser...
3288  hhd harvey gte com horace dediu writes article...
1094  what are people opinions about laser detectors...
3507  message rhhinn kralizec zeta org references qg...
                                                   Text
5218  jovanovic nick yale edu nick jovanovic writes ...
4060  article rjpuinnmij shelley washington edu krya...
1346  accounts anti armenian human right violations ...
3454  distribution world message apr kelvin jpl nasa...
3582  maildoor waflinemail kris gleason said what wi...
1997    2
1391    2
1837    2
2871    3
2733    3
Name: Document, dtype: int64
5897    6
3800    4
5646    6
4466    5
2330    3
Name: Document, dtype: int64


In [55]:
##Metrics: Multiclassification Metric 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score, precision_score, accuracy_score

def MetricCalculation(y_train,pred_train,y_test,pred_test,ModelMethodName):

    prediction=confusion_matrix(y_train, pred_train) #get confusion matrix for train predictions
    print("Train_Confusion Matrix:\n",prediction,"\n")

    acc = accuracy_score(y_train, pred_train)
    rec = recall_score(y_train, pred_train,average=None)
    prec = precision_score(y_train, pred_train,average=None)

    print("Results of",ModelMethodName," on train data:","\nAccuracy:",acc, "\nRecall:",rec, "\nPrecision:",prec , "\n")
    
    prediction = confusion_matrix(y_test,pred_test) ##get confusion matrix for test predictions
    print("Test_Confusion matrix:\n", prediction,"\n")

    acc = accuracy_score(y_test,pred_test)
    rec = recall_score(y_test,pred_test,average=None)
    prec=precision_score(y_test,pred_test,average=None)
    print("Results of ",ModelMethodName," on test data:","\nAcc: ",acc,"\nRec:", rec, "\nPrec:", prec,"\n")


# Naive Bayes 

In [56]:
from sklearn.naive_bayes import MultinomialNB

def NaiveBayes(X_train,X_test,y_train,y_test):
    nb_clf = MultinomialNB().fit(X_train, y_train) #nb_clf is the classifier
    pred_train = nb_clf.predict(X_train) #get predictions on train data
    pred_test = nb_clf.predict(X_test) #predict on test data    
    print("Naive Bayes")
    MetricCalculation(y_train,pred_train,y_test,pred_test,"Naive Bayes' ")

# Logistic Regression

In [57]:
from sklearn import linear_model
def LogisticRegression(X_train,X_test,y_train,y_test):
    logreg_train = linear_model.LogisticRegression()
    lr_clf = logreg_train.fit(X_train, y_train) #fit logreg model on train data
    pred_lr_train=lr_clf.predict(X_train) # predict on train data
    pred_lr_test=lr_clf.predict(X_test) # predict on test data
    print("Logistic Regression")
    MetricCalculation(y_train,pred_lr_train,y_test,pred_lr_test,"Logistic Regression ")

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

# Modelling

In [59]:
####Count Vectorizer
count=CountVectorizer(strip_accents='unicode',ngram_range=(1,1),stop_words='english')
tfreq=count.fit_transform(X_train.Text)
Dense_mat=tfreq.todense()
X_train_df=pd.DataFrame(Dense_mat,columns=count.get_feature_names())

print(type(X_train_df))
print(X_train_df.shape)

# Get the tfidf matrix for test documents
X_test_df = count.transform(X_test.Text)
print(type(X_test_df))
print(X_test_df.shape)

#print(X_train_df.head())
#print(X_train_df.tail())

NaiveBayes(X_train_df,X_test_df,y_train,y_test)
LogisticRegression(X_train_df,X_test_df,y_train,y_test)


<class 'pandas.core.frame.DataFrame'>
(4188, 43990)
<class 'scipy.sparse.csr.csr_matrix'>
(1796, 43990)
Naive Bayes
Train_Confusion Matrix:
 [[725   0   0   0   0   1]
 [  2 693   5   1   2   0]
 [  1   3 681   0   4   0]
 [  5   3   3 655   1   1]
 [  1   2   1   0 697   1]
 [  4   0   2   5   2 687]] 

Results of Naive Bayes'   on train data: 
Accuracy: 0.9880611270296084 
Recall: [0.99862259 0.98577525 0.98838897 0.98053892 0.99287749 0.98142857] 
Precision: [0.98238482 0.98858773 0.98410405 0.99092284 0.98725212 0.99565217] 

Test_Confusion matrix:
 [[268   0   0   0   3   3]
 [  2 290   8   1   1   1]
 [  1   6 295   2   5   1]
 [  5   3   7 300   5   1]
 [  1   2   3   3 281   5]
 [  5   3   1   1   0 283]] 

Results of  Naive Bayes'   on test data: 
Acc:  0.9560133630289532 
Rec: [0.97810219 0.95709571 0.9516129  0.93457944 0.95254237 0.96587031] 
Prec: [0.95035461 0.95394737 0.93949045 0.9771987  0.95254237 0.96258503] 

Logistic Regression
Train_Confusion Matrix:
 [[725   1   

In [31]:
###TFIDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,1),stop_words='english',vocabulary=all_words)
#print(tfidf_vectorizer.vocabulary_)
#print(tfidf_vectorizer.idf_)

tfidf = tfidf_vectorizer.fit_transform(X_train.Text)
Dense_mat = tfidf.todense()
X_train_tfidf=pd.DataFrame(Dense_mat,columns=tfidf_vectorizer.get_feature_names())

print(type(X_train_tfidf))
print(X_train_tfidf.shape)

# Get the tfidf matrix for test documents
X_test_tfidf = tfidf_vectorizer.transform(X_test.Text)
print(type(X_test_tfidf))
print(X_test_tfidf.shape)

#print(X_train_tfidf.head())
#print(X_train_tfidf.tail())

NaiveBayes(X_train_tfidf,X_test_tfidf,y_train,y_test)
LogisticRegression(X_train_tfidf,X_test_tfidf,y_train,y_test)


<class 'pandas.core.frame.DataFrame'>
(4188, 14623)
<class 'scipy.sparse.csr.csr_matrix'>
(1796, 14623)
Naive Bayes
Train_Confusion Matrix:
 [[713   2   0   0   1   2]
 [  6 698   8   0   3   0]
 [  2   7 675   0   7   0]
 [  6   2   8 675   4   0]
 [  3   4   6   4 675   0]
 [  4   0   1   0   2 670]] 

Results of Naive Bayes'   on train data: 
Accuracy: 0.9804202483285578 
Recall: [0.99303621 0.97622378 0.97684515 0.97122302 0.97543353 0.98966027] 
Precision: [0.97138965 0.97896213 0.96704871 0.99410898 0.97543353 0.99702381] 

Test_Confusion matrix:
 [[273   3   0   1   3   2]
 [  1 270  14   1   5   0]
 [  1  22 276   3   4   2]
 [  8   9   8 255  13   1]
 [  3   3   9   1 289   0]
 [  3   2   0   1   4 306]] 

Results of  Naive Bayes'   on test data: 
Acc:  0.9292873051224945 
Rec: [0.96808511 0.92783505 0.8961039  0.86734694 0.94754098 0.96835443] 
Prec: [0.94463668 0.87378641 0.8990228  0.97328244 0.90880503 0.98392283] 

Logistic Regression
Train_Confusion Matrix:
 [[710   0   